version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"          # Location of requirements.txt
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"          # Location of GitHub Actions workflows
    schedule:
      interval: "weekly"
